ensembl_gtf: /gpfs/rocket/home/a72094/annotations/GRCh38/Ensembl_90/Homo_sapiens.GRCh38.90.gtf
reference_genome: /gpfs/rocket/home/a72094/annotations/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa 
salmon_ensembl_index: /add/something/here
star_index: /gpfs/rocket/home/a72094/annotations/GRCh38/STAR_index_v90_oh74
vcf_file: /nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/SL1344/hipsci.wec.gtarray.HumanCoreExome-12_v1_0.858samples.20141111.genotypes.GRCh38.sorted.filtered.vcf.gz
chromosome_lengths: /lustre/scratch117/cellgen/team170/ka8/annotations/GRCh38/bt2-index/chromosome_lengths.txt
annotations: ["Ensembl_87", "reviseAnnotations.grp_1_contained","reviseAnnotations.grp_1_upstream","reviseAnnotations.grp_1_downstream","reviseAnnotations.grp_2_contained","reviseAnnotations.grp_2_upstream","reviseAnnotations.grp_2_downstream"]
libType: ISR
study: GEUVADIS

#Dictionary of sample names
samples:
  ERR188307: [processed/GEUVADIS/fastq/ERR188307_1.fastq.gz, processed/GEUVADIS/fastq/ERR188307_2.fastq.gz]

#Quantification
leafcutter_root: "/nfs/users/nfs_k/ka8/software/leafcutter"

#QTL mapping 
conditions: ["naive", "IFNg", "SL1344", "IFNg_SL1344", "NI", "NS", "NIS"]
#conditions: ["naive", "IFNg", "SL1344", "IFNg_SL1344"]
n_batches: 250
qtl_vcf: "/nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/SL1344/imputed_20151005/imputed.86_samples.sorted.filtered.named.vcf.gz"
cis_window: 100000
nominal_cis_window: 500000
annot_type: ["Ensembl_87", "reviseAnnotations", "leafcutter", "tpm", "featureCounts", "reviseAnnotations_groupwise"]

#Colocalisation
coloc_phenotypes: ["Ensembl_87", "reviseAnnotations", "leafcutter", "tpm", "featureCounts"]
gwas_dir: "/nfs/users/nfs_k/ka8/scratch/datasets/Inflammatory_GWAS/"
coloc_window: 2e5
gwas_traits: ["AD","CEL_2010","CEL","CD","IBD","UC","MS","NAR","PBC","PS","RA_2012","RA","SCZ","SLE","T1D","T1D_2","T2D_1","T2D","UC_2012","UC_2014","CAD","MI","CRE","CRP","GLU","HDL","HGB","HOMA_b","HOMA_ir","IL6","INS","MCHC","MCH","MCV","PCV","PLT","RBC","TC","TG","UA","WBC","LDL","CAD_2017"]

#ASE quantification:
fasta: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa
ase_vcf: "/nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/SL1344/imputed_20151005/imputed.86_samples.snps_only.vcf.gz"


